import React, { useState, useEffect, useMemo } from 'react';
import {
  X,
  Printer,
  FileCheck,
  Lock,
  User,
  MapPin,
  Calendar,
  FileText,
  Stethoscope,
  Sparkles,
  ShieldCheck,
  CheckCircle2,
  AlertCircle
} from 'lucide-react';
import {
  LetterType,
  MedicalLetterItem
} from '../../types/letterTypes';
import {
  getCategoryForType,
  getLetterTypeLabel,
  MASTER_LETTER_DOCTORS,
  MASTER_PATIENTS,
  getAutoGeneratedLetterNumber,
  commitNextSequenceForType
} from '../../data/letterData';

interface AutoNumberedLetterModalProps {
  isOpen: boolean;
  onClose: () => void;
  existingLetters: MedicalLetterItem[];
  onSaveAndPrint: (savedLetter: MedicalLetterItem) => void;
  defaultType?: LetterType;
}

export const AutoNumberedLetterModal: React.FC<AutoNumberedLetterModalProps> = ({
  isOpen,
  onClose,
  existingLetters,
  onSaveAndPrint,
  defaultType = 'SKBN'
}) => {
  const [jenisSurat, setJenisSurat] = useState<LetterType>(defaultType);
  const [currentSeq, setCurrentSeq] = useState<number>(1);
  const [nomorSurat, setNomorSurat] = useState<string>('');
  const [tanggalSurat, setTanggalSurat] = useState<string>(
    new Date().toISOString().split('T')[0]
  );

  // Form Input Pasien
  const [namaPasien, setNamaPasien] = useState('');
  const [tempatLahir, setTempatLahir] = useState('Lamongan');
  const [tanggalLahir, setTanggalLahir] = useState('1995-05-15');
  const [umur, setUmur] = useState<number>(31);
  const [jenisKelamin, setJenisKelamin] = useState<'Laki-laki' | 'Perempuan'>('Laki-laki');
  const [pekerjaan, setPekerjaan] = useState('Karyawan Swasta');
  const [alamat, setAlamat] = useState('');
  const [keperluan, setKeperluan] = useState('Persyaratan Melamar Pekerjaan / Seleksi Pegawai');
  const [noHp, setNoHp] = useState('0812-3456-7890');
  const [noRm, setNoRm] = useState('');
  const [nik, setNik] = useState('');

  // Dokter Penandatangan
  const [dokterId, setDokterId] = useState(MASTER_LETTER_DOCTORS[0].id);

  // SKBN Parameters (Default: Semua Negatif)
  const [skbnAmp, setSkbnAmp] = useState<'Negatif' | 'Positif'>('Negatif');
  const [skbnMet, setSkbnMet] = useState<'Negatif' | 'Positif'>('Negatif');
  const [skbnCoc, setSkbnCoc] = useState<'Negatif' | 'Positif'>('Negatif');
  const [skbnThc, setSkbnThc] = useState<'Negatif' | 'Positif'>('Negatif');
  const [skbnMop, setSkbnMop] = useState<'Negatif' | 'Positif'>('Negatif');
  const [skbnBzo, setSkbnBzo] = useState<'Negatif' | 'Positif'>('Negatif');
  const [skbnKesimpulan, setSkbnKesimpulan] = useState(
    'Dinyatakan BEBAS DARI PENYALAHGUNAAN NARKOTIKA & ZAT ADIKTIF'
  );

  // Error validation state
  const [errors, setErrors] = useState<Record<string, string>>({});

  // Hitung umur otomatis dari tanggal lahir
  useEffect(() => {
    if (tanggalLahir) {
      const birth = new Date(tanggalLahir);
      const now = new Date();
      let age = now.getFullYear() - birth.getFullYear();
      const m = now.getMonth() - birth.getMonth();
      if (m < 0 || (m === 0 && now.getDate() < birth.getDate())) {
        age--;
      }
      if (!isNaN(age) && age > 0) {
        setUmur(age);
      }
    }
  }, [tanggalLahir]);

  // Recalculate auto-generated nomor surat whenever jenisSurat changes or modal opens
  useEffect(() => {
    if (isOpen) {
      const { nomorSurat: autoNo, seq } = getAutoGeneratedLetterNumber(
        jenisSurat,
        existingLetters
      );
      setNomorSurat(autoNo);
      setCurrentSeq(seq);
      setErrors({});
    }
  }, [isOpen, jenisSurat, existingLetters]);

  // Quick autofill from master patients
  const handleSelectMasterPatient = (patientRm: string) => {
    const found = MASTER_PATIENTS.find((p) => p.noRm === patientRm);
    if (found) {
      setNamaPasien(found.nama);
      setTempatLahir(found.tempatLahir);
      setTanggalLahir(found.tanggalLahir);
      setUmur(found.umur);
      setJenisKelamin(found.jenisKelamin);
      setPekerjaan(found.pekerjaan);
      setAlamat(found.alamat);
      setNoHp(found.noHp);
      setNoRm(found.noRm);
      setNik(found.nik);
    }
  };

  const handleSetAllNegative = () => {
    setSkbnAmp('Negatif');
    setSkbnMet('Negatif');
    setSkbnCoc('Negatif');
    setSkbnThc('Negatif');
    setSkbnMop('Negatif');
    setSkbnBzo('Negatif');
    setSkbnKesimpulan('Dinyatakan BEBAS DARI PENYALAHGUNAAN NARKOTIKA & ZAT ADIKTIF');
  };

  const selectedDoctor = useMemo(() => {
    return (
      MASTER_LETTER_DOCTORS.find((d) => d.id === dokterId) ||
      MASTER_LETTER_DOCTORS[0]
    );
  }, [dokterId]);

  // Validasi & Simpan/Kunci Dokumen
  const handleSubmitAndPrint = (e: React.FormEvent) => {
    e.preventDefault();

    const newErrors: Record<string, string> = {};
    if (!namaPasien.trim()) newErrors.namaPasien = 'Nama lengkap pasien wajib diisi';
    if (!tempatLahir.trim()) newErrors.tempatLahir = 'Tempat lahir wajib diisi';
    if (!tanggalLahir) newErrors.tanggalLahir = 'Tanggal lahir wajib diisi';
    if (!alamat.trim()) newErrors.alamat = 'Alamat lengkap pasien wajib diisi';
    if (!keperluan.trim()) newErrors.keperluan = 'Keperluan pembuatan surat wajib diisi';

    if (Object.keys(newErrors).length > 0) {
      setErrors(newErrors);
      return;
    }

    // 1. Kunci nomor urut ke database localStorage agar nomor berikutnya berlanjut (+1)
    commitNextSequenceForType(jenisSurat, currentSeq);

    // 2. Susun objek dokumen resmi
    const category = getCategoryForType(jenisSurat);
    const newDocument: MedicalLetterItem = {
      id: `letter-${Date.now()}-${Math.random().toString(36).substr(2, 6)}`,
      nomorSurat: nomorSurat,
      kategori: category,
      jenisSurat: jenisSurat,
      tanggalSurat: tanggalSurat,
      namaPasien: namaPasien.trim().toUpperCase(),
      tempatLahir: tempatLahir.trim(),
      tanggalLahir: tanggalLahir,
      umur: umur,
      jenisKelamin: jenisKelamin,
      pekerjaan: pekerjaan.trim(),
      alamat: alamat.trim(),
      keperluan: keperluan.trim(),
      noHp: noHp.trim() || undefined,
      noRm: noRm.trim() || `RM-${Math.floor(100000 + Math.random() * 900000)}`,
      nik: nik.trim() || '3524050000000001',
      dokterNama: selectedDoctor.nama,
      dokterSip: selectedDoctor.sip,
      dokterJabatan: selectedDoctor.jabatan,
      createdAt: new Date().toISOString(),
      updatedAt: new Date().toISOString(),

      // Parameter spesifik SKBN
      skbnParams:
        jenisSurat === 'SKBN'
          ? {
              amp: skbnAmp,
              met: skbnMet,
              coc: skbnCoc,
              thc: skbnThc,
              mop: skbnMop,
              bzo: skbnBzo,
              metode: 'Rapid Diagnostic Multi-Panel Urine Strip (6 Parameter)',
              spesimen: 'Urine Segar',
              kesimpulan: skbnKesimpulan
            }
          : undefined,

      // Parameter default Surat Sehat jika dipilih
      sehatParams:
        jenisSurat === 'SEHAT'
          ? {
              tinggiBadan: 168,
              beratBadan: 64,
              tekananDarah: '120/80 mmHg',
              nadi: '80 x/menit',
              golonganDarah: 'O',
              butaWarna: 'Tidak Buta Warna (Normal)',
              statusKesehatan: 'SEHAT Jasmani dan Rohani'
            }
          : undefined,

      // Parameter default Surat Dokter jika dipilih
      dokterParams:
        jenisSurat === 'DOKTER'
          ? {
              diagnosaMedis: 'Common Cold & Asthenia',
              lamaIstirahatHari: 3,
              tglMulaiIstirahat: tanggalSurat,
              tglSelesaiIstirahat: new Date(
                new Date(tanggalSurat).getTime() + 2 * 24 * 60 * 60 * 1000
              )
                .toISOString()
                .split('T')[0],
              perluIstirahat: true
            }
          : undefined
    };

    // 3. Panggil callback simpan & cetak
    onSaveAndPrint(newDocument);
  };

  if (!isOpen) return null;

  return (
    <div className="fixed inset-0 z-50 flex items-center justify-center p-3 sm:p-4 bg-slate-900/70 backdrop-blur-xs overflow-y-auto animate-in fade-in">
      <div className="bg-white rounded-2xl max-w-3xl w-full shadow-2xl border border-slate-200 flex flex-col max-h-[94vh] overflow-hidden">
        {/* Header Modal */}
        <div className="bg-gradient-to-r from-[#005d42] to-emerald-900 text-white p-4 sm:p-5 flex items-center justify-between shrink-0 shadow-xs">
          <div className="flex items-center gap-3">
            <div className="w-10 h-10 rounded-xl bg-white/10 flex items-center justify-center text-emerald-200 border border-white/20">
              <FileCheck className="w-5 h-5" />
            </div>
            <div>
              <h3 className="font-bold text-base sm:text-lg leading-tight flex items-center gap-2">
                <span>Formulir Surat Resmi RSUMB</span>
                <span className="text-[10px] uppercase font-semibold px-2 py-0.5 rounded-full bg-emerald-500/30 text-emerald-200 border border-emerald-400/30">
                  Auto-Nomor Baku
                </span>
              </h3>
              <p className="text-xs text-emerald-100/90 mt-0.5">
                Pengisian langsung di website tanpa repot edit manual di Word. Nomor surat otomatis & terkunci.
              </p>
            </div>
          </div>
          <button
            type="button"
            onClick={onClose}
            className="w-8 h-8 rounded-lg bg-white/10 hover:bg-white/20 text-white flex items-center justify-center transition-colors cursor-pointer"
            title="Tutup"
          >
            <X className="w-4 h-4" />
          </button>
        </div>

        {/* Form Body (Scrollable) */}
        <form onSubmit={handleSubmitAndPrint} className="overflow-y-auto p-4 sm:p-6 space-y-5 text-xs flex-grow">
          {/* 1. Baris Pemilihan Jenis Surat & Nomor Otomatis (READ-ONLY) */}
          <div className="grid grid-cols-1 sm:grid-cols-2 gap-3.5 p-4 rounded-xl bg-slate-50 border border-slate-200/90">
            {/* Pilih Jenis Dokumen */}
            <div>
              <label className="block text-xs font-bold text-slate-800 mb-1">
                Pilih Dokumen Baku Resmi
              </label>
              <select
                value={jenisSurat}
                onChange={(e) => setJenisSurat(e.target.value as LetterType)}
                className="w-full px-3 py-2 bg-white border border-slate-300 rounded-xl text-xs font-semibold text-slate-800 focus:ring-2 focus:ring-[#005d42]/30 focus:border-[#005d42] transition-colors cursor-pointer"
              >
                <option value="SKBN">Surat Keterangan Bebas Narkoba (SKBN 6 Parameter)</option>
                <option value="SEHAT">Surat Keterangan Sehat Jasmani & Rohani</option>
                <option value="DOKTER">Surat Keterangan Sakit (Dokter)</option>
                <option value="KUASA_JR">Surat Kuasa Santunan Jasa Raharja</option>
                <option value="EDUKASI_OP2">Surat Edukasi Operasi Kedua (Laka Lantas JR)</option>
                <option value="BPJS_KK1">Form KK1 - Laporan Kecelakaan Tahap I (BPJSTK)</option>
              </select>
              <p className="text-[11px] text-slate-500 mt-1">
                Format baku SIMRS RSU Muhammadiyah Babat.
              </p>
            </div>

            {/* Bidang Nomor Surat (Terisi Otomatis & READ ONLY) */}
            <div>
              <div className="flex items-center justify-between mb-1">
                <label className="block text-xs font-bold text-slate-800 flex items-center gap-1.5">
                  <Lock className="w-3.5 h-3.5 text-emerald-700" />
                  <span>Nomor Surat Resmi (Read-Only)</span>
                </label>
                <span className="inline-flex items-center gap-1 px-2 py-0.5 rounded-full text-[10px] font-bold bg-emerald-100 text-emerald-800 border border-emerald-300">
                  <ShieldCheck className="w-3 h-3 text-emerald-600" />
                  Auto-Gen #{currentSeq}
                </span>
              </div>
              <input
                type="text"
                readOnly
                value={nomorSurat}
                className="w-full px-3 py-2 bg-emerald-50/60 border border-emerald-300 text-emerald-900 rounded-xl font-mono text-xs font-bold select-all cursor-not-allowed shadow-2xs"
                title="Nomor surat digenerate otomatis berdasarkan nomor terakhir di database dan terkunci"
              />
              <p className="text-[10.5px] text-emerald-700 mt-1 flex items-center gap-1">
                <CheckCircle2 className="w-3 h-3 shrink-0 text-emerald-600" />
                <span>Terisi otomatis berurutan dari database. Terkunci saat disimpan.</span>
              </p>
            </div>
          </div>

          {/* 2. Tanggal Surat & Auto-Fill Cepat Pasien */}
          <div className="flex flex-col sm:flex-row sm:items-center justify-between gap-3 pb-1 border-b border-slate-100">
            <div className="flex items-center gap-2">
              <Calendar className="w-4 h-4 text-slate-500" />
              <span className="font-semibold text-slate-700">Tanggal Dokumen:</span>
              <input
                type="date"
                value={tanggalSurat}
                onChange={(e) => setTanggalSurat(e.target.value)}
                className="px-2.5 py-1 bg-slate-50 border border-slate-300 rounded-lg text-xs font-medium text-slate-800"
              />
            </div>

            {/* Quick Auto-Fill */}
            <div className="flex items-center gap-2">
              <span className="text-slate-500 text-[11px]">Isi Cepat Data Pasien:</span>
              <select
                onChange={(e) => {
                  if (e.target.value) handleSelectMasterPatient(e.target.value);
                }}
                defaultValue=""
                className="px-2.5 py-1 bg-emerald-50 hover:bg-emerald-100 text-emerald-800 border border-emerald-300 rounded-lg text-xs font-semibold cursor-pointer transition-colors"
              >
                <option value="" disabled>
                  -- Pilih Pasien Terdaftar --
                </option>
                {MASTER_PATIENTS.map((p) => (
                  <option key={p.noRm} value={p.noRm}>
                    {p.nama} ({p.noRm})
                  </option>
                ))}
              </select>
            </div>
          </div>

          {/* 3. INPUT DATA PASIEN (Fokus Utama Petugas) */}
          <div className="bg-white p-4 rounded-xl border border-slate-200 shadow-2xs space-y-3.5">
            <div className="flex items-center gap-2 pb-2 border-b border-slate-100">
              <User className="w-4 h-4 text-[#005d42]" />
              <h4 className="font-bold text-sm text-slate-900">
                Data Pasien (Wajib Diisi Petugas)
              </h4>
            </div>

            {/* Nama Pasien */}
            <div>
              <label className="block text-xs font-semibold text-slate-700 mb-1">
                Nama Lengkap Pasien <span className="text-rose-500">*</span>
              </label>
              <input
                type="text"
                placeholder="Contoh: AHMAD RIFAI, S.Kom"
                value={namaPasien}
                onChange={(e) => {
                  setNamaPasien(e.target.value);
                  if (errors.namaPasien) setErrors((prev) => ({ ...prev, namaPasien: '' }));
                }}
                className={`w-full px-3 py-2 bg-slate-50 border ${
                  errors.namaPasien ? 'border-rose-400 bg-rose-50/40' : 'border-slate-300'
                } rounded-xl text-xs font-semibold text-slate-900 focus:outline-none focus:ring-2 focus:ring-[#005d42]/30 focus:border-[#005d42]`}
              />
              {errors.namaPasien && (
                <p className="text-[11px] text-rose-600 mt-1 flex items-center gap-1">
                  <AlertCircle className="w-3 h-3" />
                  {errors.namaPasien}
                </p>
              )}
            </div>

            {/* Tempat & Tanggal Lahir (TTL) */}
            <div className="grid grid-cols-1 sm:grid-cols-3 gap-3">
              <div>
                <label className="block text-xs font-semibold text-slate-700 mb-1">
                  Tempat Lahir <span className="text-rose-500">*</span>
                </label>
                <input
                  type="text"
                  placeholder="Contoh: Lamongan"
                  value={tempatLahir}
                  onChange={(e) => {
                    setTempatLahir(e.target.value);
                    if (errors.tempatLahir) setErrors((prev) => ({ ...prev, tempatLahir: '' }));
                  }}
                  className={`w-full px-3 py-2 bg-slate-50 border ${
                    errors.tempatLahir ? 'border-rose-400 bg-rose-50/40' : 'border-slate-300'
                  } rounded-xl text-xs text-slate-900 focus:outline-none focus:ring-2 focus:ring-[#005d42]/30 focus:border-[#005d42]`}
                />
                {errors.tempatLahir && (
                  <p className="text-[11px] text-rose-600 mt-1">{errors.tempatLahir}</p>
                )}
              </div>

              <div>
                <label className="block text-xs font-semibold text-slate-700 mb-1">
                  Tanggal Lahir <span className="text-rose-500">*</span>
                </label>
                <input
                  type="date"
                  value={tanggalLahir}
                  onChange={(e) => {
                    setTanggalLahir(e.target.value);
                    if (errors.tanggalLahir) setErrors((prev) => ({ ...prev, tanggalLahir: '' }));
                  }}
                  className={`w-full px-3 py-2 bg-slate-50 border ${
                    errors.tanggalLahir ? 'border-rose-400 bg-rose-50/40' : 'border-slate-300'
                  } rounded-xl text-xs text-slate-900 focus:outline-none focus:ring-2 focus:ring-[#005d42]/30 focus:border-[#005d42]`}
                />
                {errors.tanggalLahir && (
                  <p className="text-[11px] text-rose-600 mt-1">{errors.tanggalLahir}</p>
                )}
              </div>

              <div>
                <label className="block text-xs font-semibold text-slate-700 mb-1">
                  Umur (Tahun)
                </label>
                <input
                  type="number"
                  min={1}
                  max={120}
                  value={umur}
                  onChange={(e) => setUmur(parseInt(e.target.value) || 0)}
                  className="w-full px-3 py-2 bg-slate-50 border border-slate-300 rounded-xl text-xs text-slate-900 font-semibold"
                />
              </div>
            </div>

            {/* Jenis Kelamin & Pekerjaan */}
            <div className="grid grid-cols-1 sm:grid-cols-2 gap-3">
              <div>
                <label className="block text-xs font-semibold text-slate-700 mb-1">
                  Jenis Kelamin
                </label>
                <div className="flex items-center gap-4 py-1.5 px-3 bg-slate-50 rounded-xl border border-slate-300">
                  <label className="flex items-center gap-1.5 cursor-pointer font-medium text-slate-800">
                    <input
                      type="radio"
                      name="jk"
                      value="Laki-laki"
                      checked={jenisKelamin === 'Laki-laki'}
                      onChange={() => setJenisKelamin('Laki-laki')}
                      className="accent-[#005d42]"
                    />
                    <span>Laki-laki</span>
                  </label>
                  <label className="flex items-center gap-1.5 cursor-pointer font-medium text-slate-800">
                    <input
                      type="radio"
                      name="jk"
                      value="Perempuan"
                      checked={jenisKelamin === 'Perempuan'}
                      onChange={() => setJenisKelamin('Perempuan')}
                      className="accent-[#005d42]"
                    />
                    <span>Perempuan</span>
                  </label>
                </div>
              </div>

              <div>
                <label className="block text-xs font-semibold text-slate-700 mb-1">
                  Pekerjaan / Profesi
                </label>
                <input
                  type="text"
                  placeholder="Contoh: Karyawan Swasta / Mahasiswa"
                  value={pekerjaan}
                  onChange={(e) => setPekerjaan(e.target.value)}
                  className="w-full px-3 py-2 bg-slate-50 border border-slate-300 rounded-xl text-xs text-slate-900"
                />
              </div>
            </div>

            {/* Alamat Lengkap Pasien */}
            <div>
              <label className="block text-xs font-semibold text-slate-700 mb-1">
                Alamat Lengkap (Sesuai KTP) <span className="text-rose-500">*</span>
              </label>
              <textarea
                rows={2}
                placeholder="Contoh: Desa Kebalanpelang RT 02 / RW 01, Kec. Babat, Kab. Lamongan"
                value={alamat}
                onChange={(e) => {
                  setAlamat(e.target.value);
                  if (errors.alamat) setErrors((prev) => ({ ...prev, alamat: '' }));
                }}
                className={`w-full px-3 py-2 bg-slate-50 border ${
                  errors.alamat ? 'border-rose-400 bg-rose-50/40' : 'border-slate-300'
                } rounded-xl text-xs text-slate-900 focus:outline-none focus:ring-2 focus:ring-[#005d42]/30 focus:border-[#005d42]`}
              />
              {errors.alamat && (
                <p className="text-[11px] text-rose-600 mt-1 flex items-center gap-1">
                  <AlertCircle className="w-3 h-3" />
                  {errors.alamat}
                </p>
              )}
            </div>

            {/* Keperluan Surat */}
            <div>
              <label className="block text-xs font-semibold text-slate-700 mb-1">
                Keperluan Pembuatan Surat <span className="text-rose-500">*</span>
              </label>
              <input
                type="text"
                placeholder="Contoh: Persyaratan Pendaftaran Karyawan Tetap PT Petrokimia Gresik"
                value={keperluan}
                onChange={(e) => {
                  setKeperluan(e.target.value);
                  if (errors.keperluan) setErrors((prev) => ({ ...prev, keperluan: '' }));
                }}
                className={`w-full px-3 py-2 bg-slate-50 border ${
                  errors.keperluan ? 'border-rose-400 bg-rose-50/40' : 'border-slate-300'
                } rounded-xl text-xs text-slate-900 font-medium focus:outline-none focus:ring-2 focus:ring-[#005d42]/30 focus:border-[#005d42]`}
              />
              {errors.keperluan && (
                <p className="text-[11px] text-rose-600 mt-1 flex items-center gap-1">
                  <AlertCircle className="w-3 h-3" />
                  {errors.keperluan}
                </p>
              )}

              {/* Quick Preset Keperluan */}
              <div className="flex flex-wrap gap-1.5 mt-2">
                <span className="text-[10.5px] text-slate-400 self-center">Pilihan cepat:</span>
                {[
                  'Persyaratan Melamar Pekerjaan',
                  'Persyaratan Registrasi Karyawan Tetap',
                  'Pendaftaran Masuk Perguruan Tinggi',
                  'Persyaratan Pemberkasan Instansi Resmi'
                ].map((txt) => (
                  <button
                    key={txt}
                    type="button"
                    onClick={() => {
                      setKeperluan(txt);
                      setErrors((prev) => ({ ...prev, keperluan: '' }));
                    }}
                    className="px-2 py-0.5 bg-slate-100 hover:bg-emerald-50 hover:text-emerald-800 text-slate-600 border border-slate-200 rounded-md text-[10.5px] transition-colors"
                  >
                    {txt}
                  </button>
                ))}
              </div>
            </div>
          </div>

          {/* 4. PARAMETER KHUSUS SKBN (Jika SKBN dipilih) */}
          {jenisSurat === 'SKBN' && (
            <div className="bg-emerald-50/40 p-4 rounded-xl border border-emerald-200 space-y-3">
              <div className="flex items-center justify-between">
                <div className="flex items-center gap-2">
                  <ShieldCheck className="w-4 h-4 text-[#005d42]" />
                  <h4 className="font-bold text-xs text-emerald-950 uppercase tracking-wide">
                    Hasil Uji Laboratorium Toksikologi Urin (6 Parameter Baku)
                  </h4>
                </div>
                <button
                  type="button"
                  onClick={handleSetAllNegative}
                  className="px-2.5 py-1 bg-white hover:bg-emerald-100 text-[#005d42] border border-emerald-300 rounded-lg text-[11px] font-bold shadow-2xs transition-colors cursor-pointer"
                >
                  ✓ Set Semua Negatif (-)
                </button>
              </div>

              <div className="grid grid-cols-2 sm:grid-cols-3 gap-2.5">
                {[
                  { label: 'Amphetamine (AMP)', val: skbnAmp, set: setSkbnAmp },
                  { label: 'Methamphetamine (MET)', val: skbnMet, set: setSkbnMet },
                  { label: 'Cocaine (COC)', val: skbnCoc, set: setSkbnCoc },
                  { label: 'THC / Ganja (THC)', val: skbnThc, set: setSkbnThc },
                  { label: 'Morphine (MOP)', val: skbnMop, set: setSkbnMop },
                  { label: 'Benzodiazepine (BZO)', val: skbnBzo, set: setSkbnBzo }
                ].map((item) => (
                  <div
                    key={item.label}
                    className="p-2.5 bg-white rounded-lg border border-emerald-200/80 shadow-2xs"
                  >
                    <p className="font-semibold text-[11px] text-slate-800 mb-1.5 truncate">
                      {item.label}
                    </p>
                    <div className="flex items-center gap-2">
                      <button
                        type="button"
                        onClick={() => item.set('Negatif')}
                        className={`flex-1 py-1 rounded text-center font-bold text-[11px] transition-all ${
                          item.val === 'Negatif'
                            ? 'bg-emerald-700 text-white shadow-xs'
                            : 'bg-slate-100 text-slate-600 hover:bg-slate-200'
                        }`}
                      >
                        Negatif (-)
                      </button>
                      <button
                        type="button"
                        onClick={() => item.set('Positif')}
                        className={`py-1 px-2 rounded text-center font-bold text-[11px] transition-all ${
                          item.val === 'Positif'
                            ? 'bg-rose-700 text-white shadow-xs'
                            : 'bg-slate-100 text-slate-600 hover:bg-rose-50'
                        }`}
                      >
                        Positif (+)
                      </button>
                    </div>
                  </div>
                ))}
              </div>

              {/* Kesimpulan Resmi SKBN */}
              <div>
                <label className="block text-xs font-semibold text-emerald-950 mb-1">
                  Kesimpulan Hasil Skrining
                </label>
                <input
                  type="text"
                  value={skbnKesimpulan}
                  onChange={(e) => setSkbnKesimpulan(e.target.value)}
                  className="w-full px-3 py-2 bg-white border border-emerald-300 rounded-xl text-xs font-bold text-emerald-900"
                />
              </div>
            </div>
          )}

          {/* 5. DOKTER PENANDATANGAN */}
          <div className="bg-slate-50 p-3.5 rounded-xl border border-slate-200 space-y-2">
            <div className="flex items-center gap-2">
              <Stethoscope className="w-4 h-4 text-[#005d42]" />
              <label className="font-bold text-xs text-slate-800">
                Dokter Penandatangan / DPJP Pemeriksa
              </label>
            </div>
            <select
              value={dokterId}
              onChange={(e) => setDokterId(e.target.value)}
              className="w-full px-3 py-2 bg-white border border-slate-300 rounded-xl text-xs font-semibold text-slate-800 focus:ring-2 focus:ring-[#005d42]/30 focus:border-[#005d42] cursor-pointer"
            >
              {MASTER_LETTER_DOCTORS.map((doc) => (
                <option key={doc.id} value={doc.id}>
                  {doc.nama} ({doc.spesialisasi}) - SIP: {doc.sip}
                </option>
              ))}
            </select>
          </div>
        </form>

        {/* Footer Actions (Auto-Generate & Lock CTA) */}
        <div className="p-4 sm:p-5 bg-slate-50 border-t border-slate-200 flex flex-col sm:flex-row items-center justify-between gap-3 shrink-0">
          <div className="text-slate-600 text-[11px] flex items-center gap-2 text-center sm:text-left">
            <Lock className="w-3.5 h-3.5 text-emerald-700 shrink-0" />
            <span>
              Nomor surat resmi <b>{nomorSurat}</b> akan dikunci dan urutan selanjutnya otomatis bertambah (+1).
            </span>
          </div>

          <div className="flex items-center gap-2 w-full sm:w-auto">
            <button
              type="button"
              onClick={onClose}
              className="flex-1 sm:flex-none px-4 py-2.5 bg-white hover:bg-slate-100 text-slate-700 font-semibold rounded-xl text-xs border border-slate-300 transition-colors cursor-pointer"
            >
              Batal
            </button>

            {/* TOMBOL UTAMA: [ 🖨️ Cetak / Simpan Document ] */}
            <button
              type="button"
              id="btn-print-save-auto-document"
              onClick={handleSubmitAndPrint}
              className="flex-1 sm:flex-none flex items-center justify-center gap-2 px-6 py-2.5 bg-[#005d42] hover:bg-[#004732] active:bg-[#003726] text-white font-bold rounded-xl text-xs shadow-md hover:shadow-lg transition-all cursor-pointer"
            >
              <Printer className="w-4 h-4" />
              <span>🖨️ Cetak / Simpan Document</span>
            </button>
          </div>
        </div>
      </div>
    </div>
  );
};
