import React, { useState, useEffect, useMemo } from 'react';
import {
  X,
  User,
  Search,
  CheckCircle2,
  Calendar,
  Phone,
  MapPin,
  Stethoscope,
  Briefcase,
  AlertCircle,
  Save,
  Printer,
  ShieldCheck,
  Building2,
  Sparkles,
  Eye,
  Maximize2,
  ZoomIn,
  ZoomOut,
  ChevronRight,
  Fingerprint,
  Bed,
  Lock,
  FileText
} from 'lucide-react';
import {
  LetterType,
  MedicalLetterItem,
  LetterCategory,
  PatientRecord
} from '../../types/letterTypes';
import {
  MASTER_PATIENTS,
  ROOM_CLASSES,
  MASTER_LETTER_DOCTORS,
  generateLetterNumber,
  getNextSequenceForType,
  commitNextSequenceForType,
  getAutoGeneratedLetterNumber,
  getCategoryForType,
  getLetterTypeLabel,
  numberToTerbilang
} from '../../data/letterData';
import { DocumentSheetRenderer } from './DocumentSheetRenderer';

interface LetterFormModalProps {
  isOpen: boolean;
  onClose: () => void;
  onSave: (letter: MedicalLetterItem, andPrint?: boolean) => void;
  editingLetter: MedicalLetterItem | null;
  initialType?: LetterType;
  totalLettersCount: number;
}

export const LetterFormModal: React.FC<LetterFormModalProps> = ({
  isOpen,
  onClose,
  onSave,
  editingLetter,
  initialType = 'BPJS_KK1',
  totalLettersCount
}) => {
  // Active Tab for responsive mobile view: 'form' | 'preview'
  const [mobileTab, setMobileTab] = useState<'form' | 'preview'>('form');

  // Preview Scale Zoom: 75, 90, 100
  const [previewZoom, setPreviewZoom] = useState<number>(90);

  // Unique session ID to prevent duplicate React key errors
  const [sessionLetterId, setSessionLetterId] = useState<string>(() =>
    editingLetter ? editingLetter.id : `letter-${Date.now()}-${Math.random().toString(36).slice(2, 9)}`
  );

  // Jenis Surat
  const [jenisSurat, setJenisSurat] = useState<LetterType>(initialType);
  const [currentSeq, setCurrentSeq] = useState<number>(1);
  const [nomorSurat, setNomorSurat] = useState('');
  const [tanggalSurat, setTanggalSurat] = useState(new Date().toISOString().split('T')[0]);

  // Pasien State (Auto-Fill)
  const [noRm, setNoRm] = useState('RM-048291');
  const [nik, setNik] = useState('3524081208920003');
  const [namaPasien, setNamaPasien] = useState('AHMAD RIFAI');
  const [tempatLahir, setTempatLahir] = useState('Lamongan');
  const [tanggalLahir, setTanggalLahir] = useState('1992-08-12');
  const [umur, setUmur] = useState(34);
  const [jenisKelamin, setJenisKelamin] = useState<'Laki-laki' | 'Perempuan'>('Laki-laki');
  const [pekerjaan, setPekerjaan] = useState('Karyawan Swasta');
  const [alamat, setAlamat] = useState('Desa Kebalanpelang RT 02 / RW 01, Babat, Lamongan');
  const [noHp, setNoHp] = useState('0812-3456-7890');
  const [noBpjs, setNoBpjs] = useState('0001827364521');
  const [keperluan, setKeperluan] = useState('Persyaratan Klaim Jaminan Resmi');

  // Dokter Penandatangan
  const [dokterId, setDokterId] = useState(MASTER_LETTER_DOCTORS[0].id);

  // 1. SKBN State
  const [skbnAmp, setSkbnAmp] = useState<'Negatif' | 'Positif'>('Negatif');
  const [skbnMet, setSkbnMet] = useState<'Negatif' | 'Positif'>('Negatif');
  const [skbnCoc, setSkbnCoc] = useState<'Negatif' | 'Positif'>('Negatif');
  const [skbnThc, setSkbnThc] = useState<'Negatif' | 'Positif'>('Negatif');
  const [skbnMop, setSkbnMop] = useState<'Negatif' | 'Positif'>('Negatif');
  const [skbnBzo, setSkbnBzo] = useState<'Negatif' | 'Positif'>('Negatif');
  const [skbnKesimpulan, setSkbnKesimpulan] = useState('Dinyatakan BEBAS DARI PENYALAHGUNAAN NARKOTIKA & ZAT ADIKTIF');

  // 2. AdMedika State
  const [admNoKartu, setAdmNoKartu] = useState('ADM-9948271038');
  const [admPerusahaan, setAdmPerusahaan] = useState('PT Asuransi Allianz Life Indonesia');
  const [admJenisLayanan, setAdmJenisLayanan] = useState<'Rawat Jalan' | 'Rawat Gigi'>('Rawat Jalan');
  const [admStatusPasien, setAdmStatusPasien] = useState<'Karyawan' | 'Istri/Suami' | 'Anak'>('Karyawan');
  const [admDiagnosa, setAdmDiagnosa] = useState('Faringitis Akut & ISPA');
  const [admIcd10, setAdmIcd10] = useState('J02.9');
  const [admDiagnosaTambahan, setAdmDiagnosaTambahan] = useState('-');
  const [admTindakan, setAdmTindakan] = useState('Pemeriksaan Fisik & Edukasi Terapi');
  const [admResep, setAdmResep] = useState('Cefixime 200mg No. X, Paracetamol 500mg No. X');
  const [admAnjuran, setAdmAnjuran] = useState('Banyak minum air hangat & istirahat teratur');
  const [admIstirahat, setAdmIstirahat] = useState<'Ya' | 'Tidak'>('Tidak');
  const [admLamaIstirahat, setAdmLamaIstirahat] = useState<number>(3);
  const [admDentalDiagnosa, setAdmDentalDiagnosa] = useState('Pulpitis Irreversibel');
  const [admDentalTindakan, setAdmDentalTindakan] = useState('Penambalan Gigi Komposit');
  const [admDentalTindakanList, setAdmDentalTindakanList] = useState<string[]>(['Konsultasi', 'Tambal Amalgam / Komposit']);
  const [admDentalGigi, setAdmDentalGigi] = useState<string[]>(['16', '26']);

  // 3. Edukasi Operasi Kedua State
  const [op2Tindakan, setOp2Tindakan] = useState('Operasi Rekonstruksi Fraktur Pasca Trauma');
  const [op2Tanggal, setOp2Tanggal] = useState('2026-09-12');
  const [op2Rs1, setOp2Rs1] = useState('RSUD dr. Soegiri Lamongan');
  const [op2SyaratJr, setOp2SyaratJr] = useState(true);
  const [op2SyaratRujukan, setOp2SyaratRujukan] = useState(true);
  const [op2SyaratLp, setOp2SyaratLp] = useState(true);
  const [op2SyaratKwitansi, setOp2SyaratKwitansi] = useState(true);
  const [op2PicJr, setOp2PicJr] = useState('Bpk. Rahmat Hidayat, S.H.');
  const [op2KontakJr, setOp2KontakJr] = useState('0812-3456-7890 (Kantor Layanan Jasa Raharja Lamongan)');
  const [op2Keluarga, setOp2Keluarga] = useState('Nur Hidayati');
  const [op2Hubungan, setOp2Hubungan] = useState('Istri Kandung');

  // 4. Kuasa Jasa Raharja State
  const [kuasaBiaya, setKuasaBiaya] = useState(18500000);
  const [kuasaTerbilang, setKuasaTerbilang] = useState(numberToTerbilang(18500000));
  const [kuasaTglMulai, setKuasaTglMulai] = useState('2026-09-05');
  const [kuasaTglSelesai, setKuasaTglSelesai] = useState('2026-09-12');
  const [kuasaPemberiNama, setKuasaPemberiNama] = useState('');
  const [kuasaPemberiNik, setKuasaPemberiNik] = useState('');
  const [kuasaPemberiHub, setKuasaPemberiHub] = useState('Pasien Sendiri');

  // 5. Titip Kelas State
  const [titipKelasKamar, setTitipKelasKamar] = useState<typeof ROOM_CLASSES[number]['kelas']>('VIP');
  const [titipHakKelas, setTitipHakKelas] = useState<'Kelas 1' | 'Kelas 2' | 'Kelas 3' | 'Non-BPJS / Umum'>('Kelas 1');
  const [titipTarif, setTitipTarif] = useState(650000);
  const [titipFasilitas, setTitipFasilitas] = useState<string>(ROOM_CLASSES[1].fasilitas);
  const [titipAlasan, setTitipAlasan] = useState('Kamar sesuai hak kelas BPJS (Kelas 1) sedang penuh terisi, pasien dititipkan sementara.');

  // 6. Pemesanan Kamar State
  const [pesanRuangan, setPesanRuangan] = useState('Ruang Perawatan Flamboyan');
  const [pesanKelasKamar, setPesanKelasKamar] = useState<typeof ROOM_CLASSES[number]['kelas']>('VIP');
  const [pesanTarif, setPesanTarif] = useState(650000);
  const [pesanFasilitas, setPesanFasilitas] = useState<string>(ROOM_CLASSES[1].fasilitas);
  const [pesanTglMasuk, setPesanTglMasuk] = useState('2026-09-08');
  const [pesanJamMasuk, setPesanJamMasuk] = useState('10:00 WIB');
  const [pesanNamaPemesan, setPesanNamaPemesan] = useState('');
  const [pesanHubunganPemesan, setPesanHubunganPemesan] = useState('Keluarga Kandung');
  const [pesanPetugas, setPesanPetugas] = useState('Siti Aminah, A.Md.Kep');

  // 7. Gagal Fingerprint State
  const [gagalNamaPj, setGagalNamaPj] = useState('Hj. Siti Mutmainnah');
  const [gagalGenderPj, setGagalGenderPj] = useState<'Lk' | 'Pr'>('Pr');
  const [gagalTglLahirPj, setGagalTglLahirPj] = useState('1970-04-15');
  const [gagalAlamatPj, setGagalAlamatPj] = useState('Desa Kebalanpelang RT 02/01 Babat');
  const [gagalNoTelpPj, setGagalNoTelpPj] = useState('0813-8877-6655');
  const [gagalHubungan, setGagalHubungan] = useState<'Ayah' | 'Ibu' | 'Suami' | 'Istri' | 'Anak' | 'Lainnya'>('Istri');
  const [gagalHubunganLain, setGagalHubunganLain] = useState('');
  const [gagalLayanan, setGagalLayanan] = useState<'IGD' | 'Ruang' | 'Klinik'>('Klinik');
  const [gagalNamaLayanan, setGagalNamaLayanan] = useState('Poli Penyakit Dalam');
  const [gagalAlasan, setGagalAlasan] = useState('Sidik jari rusak / luka / perban / lansia sensor sulit mendeteksi biometrik');
  const [gagalPetugas, setGagalPetugas] = useState('Nailul Muna, S.Tr.Kes');
  const [gagalPicKlaim, setGagalPicKlaim] = useState('Verifikator BPJS RSUMB');

  // 8. BPJS Ketenagakerjaan (KK1, KK2, KK3)
  const [kkPerusahaan, setKkPerusahaan] = useState('PT Petrokimia Gresik (Workshop Babat)');
  const [kkNpp, setKkNpp] = useState('NPP-10492817290');
  const [kk1Tgl, setKk1Tgl] = useState('2026-09-07');
  const [kk1Jam, setKk1Jam] = useState('08:45 WIB');
  const [kk1Tempat, setKk1Tempat] = useState('Area Workshop Fabrikasi Mesin');
  const [kk1Kronologi, setKk1Kronologi] = useState('Pekerja sedang mengoperasikan mesin bubut, serpihan logam mengenai tangan kanan.');
  const [kk1Cidera, setKk1Cidera] = useState('Vulnus Laceratum Regio Antebrachii et Manus Dextra');
  const [kk2Diagnosa, setKk2Diagnosa] = useState('Vulnus Laceratum Dextra dg Ruptur Parsial Tendon');
  const [kk2Stmb, setKk2Stmb] = useState<'Sementara Tidak Mampu Bekerja (STMB)' | 'Mampu Bekerja Ringan' | 'Sembuh Sempurna'>('Sementara Tidak Mampu Bekerja (STMB)');
  const [kk3Keadaan, setKk3Keadaan] = useState<any>('Sembuh tanpa cacat');
  const [kk3TglKembali, setKk3TglKembali] = useState('2026-09-20');

  // 9. Sehat & Dokter State
  const [sehatTb, setSehatTb] = useState(165);
  const [sehatBb, setSehatBb] = useState(60);
  const [sehatTd, setSehatTd] = useState('120/80 mmHg');
  const [sehatNadi, setSehatNadi] = useState('80 x/menit');
  const [sehatGolDarah, setSehatGolDarah] = useState<'A' | 'B' | 'AB' | 'O' | '-'>('O');
  const [sehatButaWarna, setSehatButaWarna] = useState<'Tidak Buta Warna (Normal)' | 'Buta Warna Parsial' | 'Buta Warna Total'>('Tidak Buta Warna (Normal)');
  const [dokterDiagnosa, setDokterDiagnosa] = useState('Dyspepsia Syndrome Akut');
  const [dokterLamaHari, setDokterLamaHari] = useState(3);
  const [dokterTglMulai, setDokterTglMulai] = useState('2026-09-07');
  const [dokterTglSelesai, setDokterTglSelesai] = useState('2026-09-09');

  // Auto-Fill function from patient database
  const handleApplyPatient = (patient: PatientRecord) => {
    setNoRm(patient.noRm);
    setNik(patient.nik);
    setNamaPasien(patient.nama);
    setTempatLahir(patient.tempatLahir);
    setTanggalLahir(patient.tanggalLahir);
    setUmur(patient.umur);
    setJenisKelamin(patient.jenisKelamin);
    setPekerjaan(patient.pekerjaan);
    setAlamat(patient.alamat);
    setNoHp(patient.noHp);
    setNoBpjs(patient.noBpjs || '');
    setKuasaPemberiNama(patient.nama);
    setKuasaPemberiNik(patient.nik);
    setPesanNamaPemesan(patient.nama);
  };

  // When room class changes in Titip Kelas
  const handleTitipKelasChange = (kelas: typeof ROOM_CLASSES[number]['kelas']) => {
    setTitipKelasKamar(kelas);
    const found = ROOM_CLASSES.find((r) => r.kelas === kelas);
    if (found) {
      setTitipTarif(found.tarif);
      setTitipFasilitas(found.fasilitas);
    }
  };

  // When room class changes in Pesan Kamar
  const handlePesanKelasChange = (kelas: typeof ROOM_CLASSES[number]['kelas']) => {
    setPesanKelasKamar(kelas);
    const found = ROOM_CLASSES.find((r) => r.kelas === kelas);
    if (found) {
      setPesanTarif(found.tarif);
      setPesanFasilitas(found.fasilitas);
    }
  };

  // When kuasaBiaya changes, update terbilang
  const handleBiayaKuasaChange = (val: number) => {
    setKuasaBiaya(val);
    setKuasaTerbilang(numberToTerbilang(val));
  };

  // Initial load / sync when modal opens or editing
  useEffect(() => {
    if (editingLetter) {
      setSessionLetterId(editingLetter.id);
      setJenisSurat(editingLetter.jenisSurat);
      setNomorSurat(editingLetter.nomorSurat);
      setTanggalSurat(editingLetter.tanggalSurat);
      setNoRm(editingLetter.noRm || '');
      setNamaPasien(editingLetter.namaPasien);
      setNik(editingLetter.nik);
      setTempatLahir(editingLetter.tempatLahir);
      setTanggalLahir(editingLetter.tanggalLahir);
      setUmur(editingLetter.umur || 30);
      setJenisKelamin(editingLetter.jenisKelamin);
      setPekerjaan(editingLetter.pekerjaan);
      setAlamat(editingLetter.alamat);
      setNoHp(editingLetter.noHp || '');
      setNoBpjs(editingLetter.noBpjs || '');
      setKeperluan(editingLetter.keperluan);

      const doc = MASTER_LETTER_DOCTORS.find((d) => d.nama === editingLetter.dokterNama);
      if (doc) setDokterId(doc.id);
    } else {
      setSessionLetterId(`letter-${Date.now()}-${Math.random().toString(36).slice(2, 9)}`);
      const type = (initialType || 'BPJS_KK1') as LetterType;
      setJenisSurat(type);
      const { nomorSurat: autoNo, seq } = getAutoGeneratedLetterNumber(type);
      setNomorSurat(autoNo);
      setCurrentSeq(seq);
      setTanggalSurat(new Date().toISOString().split('T')[0]);
      // Default initial patient
      handleApplyPatient(MASTER_PATIENTS[0]);
    }
  }, [editingLetter, initialType, isOpen]);

  // When jenisSurat changes while creating new
  const handleTypeChange = (newType: LetterType) => {
    setJenisSurat(newType);
    if (!editingLetter) {
      const { nomorSurat: autoNo, seq } = getAutoGeneratedLetterNumber(newType);
      setNomorSurat(autoNo);
      setCurrentSeq(seq);
    }
  };

  // Reactive preview object assembled continuously
  const currentDoctor = useMemo(() => {
    return MASTER_LETTER_DOCTORS.find((d) => d.id === dokterId) || MASTER_LETTER_DOCTORS[0];
  }, [dokterId]);

  const previewLetter = useMemo((): MedicalLetterItem => {
    const category = getCategoryForType(jenisSurat);
    return {
      id: editingLetter ? editingLetter.id : sessionLetterId,
      nomorSurat: nomorSurat || generateLetterNumber(jenisSurat, totalLettersCount + 1),
      kategori: category,
      jenisSurat: jenisSurat,
      tanggalSurat: tanggalSurat,
      noRm: noRm,
      namaPasien: namaPasien,
      nik: nik,
      tempatLahir: tempatLahir,
      tanggalLahir: tanggalLahir,
      umur: umur,
      jenisKelamin: jenisKelamin,
      pekerjaan: pekerjaan,
      alamat: alamat,
      noHp: noHp,
      noBpjs: noBpjs,
      keperluan: keperluan,
      dokterNama: currentDoctor.nama,
      dokterSip: currentDoctor.sip,
      dokterJabatan: currentDoctor.jabatan,
      createdAt: editingLetter ? editingLetter.createdAt : new Date().toISOString(),
      updatedAt: new Date().toISOString(),

      // Params
      skbnParams: {
        amp: skbnAmp,
        met: skbnMet,
        coc: skbnCoc,
        thc: skbnThc,
        mop: skbnMop,
        bzo: skbnBzo,
        metode: 'Rapid Diagnostic Multi-Panel Urine Strip (6 Parameter)',
        spesimen: 'Urine Segar',
        kesimpulan: skbnKesimpulan
      },
      admedikaParams: {
        noKartuAdmedika: admNoKartu,
        namaPerusahaan: admPerusahaan,
        jenisLayanan: admJenisLayanan,
        diagnosaUtama: admDiagnosa,
        kodeIcd10: admIcd10,
        tindakanMedis: admTindakan,
        resepObat: admResep,
        totalBiaya: 450000,
        statusPasien: admStatusPasien as any,
        namaKlinikRs: 'RSU Muhammadiyah Babat',
        tanggalPengobatan: tanggalSurat,
        keluhan: keperluan,
        diagnosaTambahan: admDiagnosaTambahan,
        terapi: admResep,
        anjuran: admAnjuran,
        namaDokter: currentDoctor.nama,
        suratIstirahatSakit: admIstirahat,
        lamaIstirahatHari: admLamaIstirahat,
        dentalDiagnosa: admDentalDiagnosa,
        dentalTindakan: admDentalTindakan,
        dentalJenisTindakan: admDentalTindakanList,
        dentalGigiDiperiksa: admDentalGigi
      },
      edukasiOp2Params: {
        rencanaTindakan: op2Tindakan,
        tanggalRencanaOp: op2Tanggal,
        rsPerujukPertama: op2Rs1,
        syaratJasaRaharjaMax20jt: op2SyaratJr,
        syaratRujukanFaskes1: op2SyaratRujukan,
        syaratLaporanPolisi: op2SyaratLp,
        syaratRincianBiayaRS1: op2SyaratKwitansi,
        namaPicJasaRaharja: op2PicJr,
        kontakPicJasaRaharja: op2KontakJr,
        namaKeluargaPasien: op2Keluarga,
        hubunganKeluarga: op2Hubungan,
        namaPetugasAdmisi: currentDoctor.nama
      },
      kuasaJrParams: {
        totalBiayaPerawatan: kuasaBiaya,
        terbilang: kuasaTerbilang,
        tanggalMulaiRawat: kuasaTglMulai,
        tanggalSelesaiRawat: kuasaTglSelesai,
        namaPemberiKuasa: kuasaPemberiNama || namaPasien,
        nikPemberiKuasa: kuasaPemberiNik || nik,
        hubunganPemberiKuasa: kuasaPemberiHub,
        alamatPemberiKuasa: alamat,
        noHpPemberiKuasa: noHp,
        namaPenerimaKuasa: 'Bagian Keuangan & Piutang RSUMB',
        jabatanPenerimaKuasa: 'Pejabat Keuangan Rumah Sakit',
        perluMaterai: true
      },
      titipKelasParams: {
        kelasKamarDipilih: titipKelasKamar,
        hakKelasBpjs: titipHakKelas,
        tarifPerHari: titipTarif,
        fasilitasKamar: titipFasilitas,
        alasanTitipKelas: titipAlasan,
        namaPenjamin: namaPasien,
        hubunganPenjamin: 'Pasien / Keluarga',
        alamatPenjamin: alamat,
        noHpPenjamin: noHp,
        setujuSelisihBiaya: true
      },
      pesanKamarParams: {
        kelasKamarDipilih: pesanKelasKamar,
        tarifPerHari: pesanTarif,
        fasilitasKamar: pesanFasilitas,
        tanggalRencanaMasuk: pesanTglMasuk,
        jamRencanaMasuk: pesanJamMasuk,
        estimasiLamaInapHari: 3,
        diagnosaAwal: 'Observasi Perawatan Medis',
        dokterPengirim: currentDoctor.nama,
        namaPemesan: pesanNamaPemesan || namaPasien,
        hubunganPemesan: pesanHubunganPemesan,
        noHpPemesan: noHp,
        ruanganDipesan: pesanRuangan,
        namaPetugas: pesanPetugas
      },
      gagalFingerprintParams: {
        alasanGagal: gagalAlasan,
        alasanKustom: gagalAlasan,
        penanggungJawabKlaim: 'Petugas Admisi',
        namaPetugas: gagalPetugas,
        nomorSep: '0184R0010926V001928',
        tujuanPoli: gagalNamaLayanan,
        namaPenjamin: gagalNamaPj,
        hubunganPenjamin: gagalHubungan,
        pernyataanKebenaran: true,
        namaPenanggungJawab: gagalNamaPj,
        genderPenanggungJawab: gagalGenderPj,
        tglLahirPenanggungJawab: gagalTglLahirPj,
        alamatPenanggungJawab: gagalAlamatPj,
        noTelpPenanggungJawab: gagalNoTelpPj,
        hubunganPenanggungJawab: gagalHubungan,
        hubunganLainnya: gagalHubunganLain,
        layananTipe: gagalLayanan,
        namaLayanan: gagalNamaLayanan,
        namaPasien: namaPasien,
        nomorKartuBpjs: noBpjs,
        alasanKesulitan: gagalAlasan,
        namaPicKlaim: gagalPicKlaim
      },
      bpjsKk1Params: {
        namaPerusahaan: kkPerusahaan,
        nppBpjsTk: kkNpp,
        tanggalKecelakaan: kk1Tgl,
        jamKecelakaan: kk1Jam,
        tempatKecelakaan: kk1Tempat,
        kronologiSingkat: kk1Kronologi,
        bagianTubuhCidera: kk1Cidera,
        faskesPertama: 'IGD RSU Muhammadiyah Babat'
      },
      bpjsKk2Params: {
        namaPerusahaan: kkPerusahaan,
        nppBpjsTk: kkNpp,
        tanggalPemeriksaan: tanggalSurat,
        diagnosaKecelakaanKerja: kk2Diagnosa,
        tindakanMedisDilakukan: 'Debridement & Penjahitan Luka, Imobilisasi Splint',
        kondisiFisikSaatIni: 'Luka terawat baik, nyeri berkurang',
        lamaPerawatanHari: 5,
        statusKemampuanBekerja: kk2Stmb,
        tanggalMulaiStmb: tanggalSurat,
        tanggalSelesaiStmb: '2026-09-15',
        tanggalKecelakaan: kk1Tgl,
        kondisiTerakhir: 'Masih dalam pengobatan'
      },
      bpjsKk3Params: {
        namaPerusahaan: kkPerusahaan,
        nppBpjsTk: kkNpp,
        tanggalPenyelesaianKasus: tanggalSurat,
        keadaanAkhirPasien: (kk3Keadaan === 'Sembuh tanpa cacat' ? 'Sembuh tanpa cacat' : 'Cacat fungsi sebagian') as any,
        tanggalKembaliBekerja: kk3TglKembali,
        evaluasiMedisAkhir: 'Luka telah sembuh sempurna, fungsi motorik normal.',
        tipeDokter: 'Dokter pemeriksa',
        tanggalKecelakaan: kk1Tgl,
        anamnesa: kk1Kronologi,
        pemeriksaanFisik: 'Kondisi umum baik, luka bedah kering tanpa infeksi.',
        tindakanMedis: 'Evaluasi post bedah debridement dan fisioterapi bertahap.',
        diagnosis: kk2Diagnosa,
        namaDokter: currentDoctor.nama
      },
      sehatParams: {
        tinggiBadan: sehatTb,
        beratBadan: sehatBb,
        tekananDarah: sehatTd,
        nadi: sehatNadi,
        golonganDarah: sehatGolDarah,
        butaWarna: sehatButaWarna,
        statusKesehatan: 'SEHAT Jasmani dan Rohani'
      },
      dokterParams: {
        diagnosaMedis: dokterDiagnosa,
        lamaIstirahatHari: dokterLamaHari,
        tglMulaiIstirahat: dokterTglMulai,
        tglSelesaiIstirahat: dokterTglSelesai,
        perluIstirahat: true
      }
    };
  }, [
    jenisSurat,
    nomorSurat,
    tanggalSurat,
    noRm,
    namaPasien,
    nik,
    tempatLahir,
    tanggalLahir,
    umur,
    jenisKelamin,
    pekerjaan,
    alamat,
    noHp,
    noBpjs,
    keperluan,
    currentDoctor,
    skbnAmp,
    skbnMet,
    skbnCoc,
    skbnThc,
    skbnMop,
    skbnBzo,
    skbnKesimpulan,
    admNoKartu,
    admPerusahaan,
    admJenisLayanan,
    admStatusPasien,
    admDiagnosa,
    admIcd10,
    admDiagnosaTambahan,
    admTindakan,
    admResep,
    admAnjuran,
    admIstirahat,
    admLamaIstirahat,
    admDentalDiagnosa,
    admDentalTindakan,
    admDentalTindakanList,
    admDentalGigi,
    op2Tindakan,
    op2Tanggal,
    op2Rs1,
    op2SyaratJr,
    op2SyaratRujukan,
    op2SyaratLp,
    op2SyaratKwitansi,
    op2PicJr,
    op2KontakJr,
    op2Keluarga,
    op2Hubungan,
    kuasaBiaya,
    kuasaTerbilang,
    kuasaTglMulai,
    kuasaTglSelesai,
    kuasaPemberiNama,
    kuasaPemberiNik,
    kuasaPemberiHub,
    titipKelasKamar,
    titipHakKelas,
    titipTarif,
    titipFasilitas,
    titipAlasan,
    pesanRuangan,
    pesanKelasKamar,
    pesanTarif,
    pesanFasilitas,
    pesanTglMasuk,
    pesanJamMasuk,
    pesanNamaPemesan,
    pesanHubunganPemesan,
    pesanPetugas,
    gagalNamaPj,
    gagalGenderPj,
    gagalTglLahirPj,
    gagalAlamatPj,
    gagalNoTelpPj,
    gagalHubungan,
    gagalHubunganLain,
    gagalLayanan,
    gagalNamaLayanan,
    gagalAlasan,
    gagalPetugas,
    gagalPicKlaim,
    kkPerusahaan,
    kkNpp,
    kk1Tgl,
    kk1Jam,
    kk1Tempat,
    kk1Kronologi,
    kk1Cidera,
    kk2Diagnosa,
    kk2Stmb,
    kk3Keadaan,
    kk3TglKembali,
    sehatTb,
    sehatBb,
    sehatTd,
    sehatNadi,
    sehatGolDarah,
    sehatButaWarna,
    dokterDiagnosa,
    dokterLamaHari,
    dokterTglMulai,
    dokterTglSelesai,
    editingLetter,
    totalLettersCount
  ]);

  const handlePrint = () => {
    window.print();
  };

  const handleFormSubmit = (andPrint: boolean) => {
    if (!namaPasien.trim() || !nik.trim()) {
      alert('Mohon lengkapi Nama Pasien dan NIK terlebih dahulu.');
      return;
    }
    if (!editingLetter) {
      commitNextSequenceForType(jenisSurat, currentSeq);
    }
    const finalLetter: MedicalLetterItem = {
      ...previewLetter,
      id: editingLetter
        ? editingLetter.id
        : sessionLetterId && sessionLetterId !== 'preview-temp-id'
        ? sessionLetterId
        : `letter-${Date.now()}-${Math.random().toString(36).slice(2, 9)}`
    };
    onSave(finalLetter, andPrint);
  };

  if (!isOpen) return null;

  return (
    <div className="fixed inset-0 z-50 flex items-center justify-center bg-slate-950/80 backdrop-blur-xs p-1 sm:p-2 lg:p-4 overflow-hidden print:p-0 print:m-0 print:bg-white print:static">
      <div className="bg-white rounded-2xl shadow-2xl border border-slate-200 w-full max-w-[98vw] lg:max-w-[96vw] xl:max-w-[1700px] h-[96vh] flex flex-col overflow-hidden animate-in fade-in zoom-in-95 duration-150 print:max-h-none print:h-auto print:border-none print:shadow-none print:w-full print:max-w-none">
        
        {/* Top Studio Header */}
        <div className="bg-gradient-to-r from-[#005d42] via-[#004732] to-slate-900 text-white px-4 py-3 flex items-center justify-between shrink-0 print:hidden no-print">
          <div className="flex items-center gap-3">
            <div className="w-9 h-9 rounded-xl bg-white/15 flex items-center justify-center text-emerald-300">
              <Stethoscope className="w-5 h-5" />
            </div>
            <div>
              <div className="flex items-center gap-2">
                <h2 className="text-sm sm:text-base font-bold">
                  {editingLetter ? 'Edit Dokumen Layanan RSUMB' : 'Editor Form & Cetak Dokumen'}
                </h2>
                <span className="bg-emerald-500/20 text-emerald-300 text-[10px] font-bold px-2 py-0.5 rounded-full border border-emerald-400/30">
                  Presisi 100% Sesuai Asli
                </span>
              </div>
              <p className="text-[11px] text-emerald-100/80 font-mono">
                {previewLetter.nomorSurat} &bull; {getLetterTypeLabel(jenisSurat)}
              </p>
            </div>
          </div>

          {/* Quick Tabs on Mobile Screen */}
          <div className="flex lg:hidden bg-white/10 p-0.5 rounded-lg text-xs">
            <button
              type="button"
              onClick={() => setMobileTab('form')}
              className={`px-3 py-1 rounded-md font-semibold ${mobileTab === 'form' ? 'bg-white text-emerald-950 shadow-xs' : 'text-white'}`}
            >
              ✏️ Input Form
            </button>
            <button
              type="button"
              onClick={() => setMobileTab('preview')}
              className={`px-3 py-1 rounded-md font-semibold ${mobileTab === 'preview' ? 'bg-white text-emerald-950 shadow-xs' : 'text-white'}`}
            >
              📄 Pratinjau & Cetak
            </button>
          </div>

          {/* Action Buttons Top */}
          <div className="flex items-center gap-2">
            <button
              type="button"
              onClick={handlePrint}
              className="flex items-center gap-1.5 px-3 sm:px-4 py-1.5 bg-emerald-400 hover:bg-emerald-300 text-slate-900 rounded-lg text-xs font-bold transition-all shadow-md shadow-emerald-950/20 active:scale-95"
            >
              <Printer className="w-4 h-4" />
              <span>Cetak (window.print)</span>
            </button>

            <button
              type="button"
              onClick={() => handleFormSubmit(false)}
              className="hidden sm:flex items-center gap-1.5 px-3 py-1.5 bg-white/15 hover:bg-white/25 text-white border border-white/20 rounded-lg text-xs font-semibold transition-colors"
            >
              <Save className="w-3.5 h-3.5 text-emerald-300" />
              <span>Simpan</span>
            </button>

            <button
              type="button"
              onClick={onClose}
              className="w-8 h-8 rounded-lg bg-white/10 hover:bg-white/20 text-white flex items-center justify-center transition-colors ml-1"
            >
              <X className="w-5 h-5" />
            </button>
          </div>
        </div>

        {/* Dual-Pane Studio Body */}
        <div className="flex-1 grid grid-cols-1 lg:grid-cols-12 overflow-hidden">
          
          {/* ======================================================== */}
          {/* SISI KIRI: FORM INPUT DYNAMIC RINGKAS                    */}
          {/* ======================================================== */}
          <div className={`lg:col-span-5 flex flex-col border-r border-slate-200 bg-slate-50/70 overflow-y-auto p-4 space-y-4 print:hidden no-print ${mobileTab === 'preview' ? 'hidden lg:flex' : 'flex'}`}>
            
            {/* Header Pilihan Template Dokumen */}
            <div className="bg-white p-3.5 rounded-xl border border-slate-200 shadow-2xs space-y-2.5">
              <div className="flex items-center justify-between">
                <label className="text-xs font-bold text-slate-800 uppercase flex items-center gap-1.5">
                  <FileText className="w-4 h-4 text-emerald-700" />
                  <span>Pilih Template Dokumen Resmi</span>
                </label>
                <span className="text-[10px] text-slate-500 font-mono">
                  {totalLettersCount + 1} Terbit
                </span>
              </div>

              <select
                value={jenisSurat}
                onChange={(e) => handleTypeChange(e.target.value as LetterType)}
                className="w-full px-3 py-2 bg-emerald-50/50 border-2 border-emerald-600/60 rounded-lg text-xs font-bold text-emerald-950 focus:outline-none focus:ring-2 focus:ring-emerald-500"
              >
                <optgroup label="📋 BPJS Ketenagakerjaan (Formulir Resmi Kemnaker/BPJS TK)">
                  <option value="BPJS_KK1">Formulir 3 KK 1 (Kecelakaan Kerja Tahap I)</option>
                  <option value="BPJS_KK2">Formulir 3a KK 2 (Kecelakaan Kerja Tahap II)</option>
                  <option value="BPJS_KK3">Formulir 3b KK 3 (Kecelakaan Kerja Tahap III / Selesai)</option>
                </optgroup>
                <optgroup label="🏨 Pelayanan Admisi & Rawat Inap RSUMB">
                  <option value="PESAN_KAMAR">Bukti Pemesanan Kamar Rawat Inap RSUMB</option>
                  <option value="GAGAL_FINGERPRINT">Pernyataan Tidak Bisa Rekam Sidik Jari (Fingerprint)</option>
                  <option value="TITIP_KELAS">Surat Pernyataan Titip Kelas Rawat Inap BPJS</option>
                </optgroup>
                <optgroup label="🩺 Formulir Medis & Klaim Asuransi">
                  <option value="ADMEDIKA">Formulir Klaim Rawat Jalan & Gigi AdMedika</option>
                  <option value="SKBN">Surat Keterangan Bebas Narkoba (SKBN 6 Parameter)</option>
                  <option value="SEHAT">Surat Keterangan Sehat Jasmani & Rohani</option>
                  <option value="DOKTER">Surat Keterangan Sakit Dokter</option>
                </optgroup>
                <optgroup label="⚖️ Jasa Raharja & Penjaminan Khusus">
                  <option value="EDUKASI_OP2">Surat Edukasi Operasi Kedua (Laka Lantas JR)</option>
                  <option value="KUASA_JR">Surat Kuasa Penagihan Biaya Jasa Raharja</option>
                </optgroup>
              </select>

              <div className="grid grid-cols-2 gap-2 text-xs">
                <div>
                  <div className="flex items-center justify-between mb-0.5">
                    <label className="block text-[10px] font-semibold text-slate-700 flex items-center gap-1">
                      <Lock className="w-3 h-3 text-emerald-700" />
                      <span>Nomor Dokumen (Read-Only)</span>
                    </label>
                    <span className="text-[9px] font-bold text-emerald-700 bg-emerald-50 px-1 py-0.2 rounded border border-emerald-200">
                      Auto-Gen #{currentSeq}
                    </span>
                  </div>
                  <input
                    type="text"
                    readOnly
                    value={nomorSurat}
                    className="w-full px-2 py-1 bg-emerald-50/70 border border-emerald-300 text-emerald-900 rounded font-mono text-xs font-bold select-all cursor-not-allowed shadow-2xs"
                    title="Nomor surat digenerate otomatis berdasarkan urutan terakhir dan terkunci di database"
                  />
                </div>
                <div>
                  <label className="block text-[10px] font-semibold text-slate-500 mb-0.5">Tanggal Dokumen</label>
                  <input
                    type="date"
                    value={tanggalSurat}
                    onChange={(e) => setTanggalSurat(e.target.value)}
                    className="w-full px-2 py-1 bg-slate-50 border border-slate-300 rounded text-xs"
                  />
                </div>
              </div>
            </div>

            {/* CARD 1: DATA PASIEN (Quick Auto-Fill Master Pasien RSUMB) */}
            <div className="bg-white p-3.5 rounded-xl border border-slate-200 shadow-2xs space-y-2.5">
              <div className="flex items-center justify-between">
                <h3 className="text-xs font-bold text-slate-800 uppercase flex items-center gap-1.5">
                  <User className="w-4 h-4 text-emerald-700" />
                  <span>Identitas Pasien (Titik-Titik)</span>
                </h3>
                <div className="flex items-center gap-1">
                  <span className="text-[10px] text-slate-500">Auto-Fill:</span>
                  <select
                    onChange={(e) => {
                      const found = MASTER_PATIENTS.find((p) => p.noRm === e.target.value);
                      if (found) handleApplyPatient(found);
                    }}
                    value={noRm}
                    className="text-[10.5px] font-bold px-1.5 py-0.5 bg-emerald-50 border border-emerald-300 text-emerald-800 rounded"
                  >
                    {MASTER_PATIENTS.map((p) => (
                      <option key={p.noRm} value={p.noRm}>
                        {p.noRm} - {p.nama}
                      </option>
                    ))}
                  </select>
                </div>
              </div>

              <div className="grid grid-cols-2 gap-2 text-xs">
                <div>
                  <label className="block text-[10px] font-semibold text-slate-600 mb-0.5">No. Rekam Medis (RM)</label>
                  <input
                    type="text"
                    value={noRm}
                    onChange={(e) => setNoRm(e.target.value)}
                    className="w-full px-2.5 py-1 bg-white border border-slate-300 rounded font-mono font-bold text-slate-800"
                    placeholder="RM-048291"
                  />
                </div>
                <div>
                  <label className="block text-[10px] font-semibold text-slate-600 mb-0.5">NIK KTP (16 Digit)</label>
                  <input
                    type="text"
                    value={nik}
                    onChange={(e) => setNik(e.target.value)}
                    className="w-full px-2.5 py-1 bg-white border border-slate-300 rounded font-mono text-slate-800"
                    placeholder="3524..."
                  />
                </div>
                <div className="col-span-2">
                  <label className="block text-[10px] font-semibold text-slate-600 mb-0.5">Nama Lengkap Pasien</label>
                  <input
                    type="text"
                    value={namaPasien}
                    onChange={(e) => setNamaPasien(e.target.value)}
                    className="w-full px-2.5 py-1 bg-white border border-slate-300 rounded font-bold uppercase text-slate-900"
                    placeholder="Nama Lengkap"
                  />
                </div>
                <div>
                  <label className="block text-[10px] font-semibold text-slate-600 mb-0.5">Tanggal Lahir & Umur</label>
                  <div className="flex gap-1">
                    <input
                      type="date"
                      value={tanggalLahir}
                      onChange={(e) => setTanggalLahir(e.target.value)}
                      className="w-full px-2 py-1 bg-white border border-slate-300 rounded text-xs"
                    />
                    <input
                      type="number"
                      value={umur}
                      onChange={(e) => setUmur(Number(e.target.value))}
                      className="w-14 px-1 py-1 bg-white border border-slate-300 rounded text-xs text-center"
                      title="Umur"
                    />
                  </div>
                </div>
                <div>
                  <label className="block text-[10px] font-semibold text-slate-600 mb-0.5">Jenis Kelamin</label>
                  <div className="flex gap-2 pt-1">
                    <label className="flex items-center gap-1 text-[11px] cursor-pointer">
                      <input
                        type="radio"
                        name="jk"
                        checked={jenisKelamin === 'Laki-laki'}
                        onChange={() => setJenisKelamin('Laki-laki')}
                      />
                      <span>Laki-laki</span>
                    </label>
                    <label className="flex items-center gap-1 text-[11px] cursor-pointer">
                      <input
                        type="radio"
                        name="jk"
                        checked={jenisKelamin === 'Perempuan'}
                        onChange={() => setJenisKelamin('Perempuan')}
                      />
                      <span>Perempuan</span>
                    </label>
                  </div>
                </div>
                <div>
                  <label className="block text-[10px] font-semibold text-slate-600 mb-0.5">No. Kartu BPJS / Asuransi</label>
                  <input
                    type="text"
                    value={noBpjs}
                    onChange={(e) => setNoBpjs(e.target.value)}
                    className="w-full px-2.5 py-1 bg-white border border-slate-300 rounded font-mono text-slate-800"
                    placeholder="0001827..."
                  />
                </div>
                <div>
                  <label className="block text-[10px] font-semibold text-slate-600 mb-0.5">No. HP / Telepon</label>
                  <input
                    type="text"
                    value={noHp}
                    onChange={(e) => setNoHp(e.target.value)}
                    className="w-full px-2.5 py-1 bg-white border border-slate-300 rounded text-slate-800"
                    placeholder="0812..."
                  />
                </div>
                <div className="col-span-2">
                  <label className="block text-[10px] font-semibold text-slate-600 mb-0.5">Alamat Domisili Lengkap</label>
                  <input
                    type="text"
                    value={alamat}
                    onChange={(e) => setAlamat(e.target.value)}
                    className="w-full px-2.5 py-1 bg-white border border-slate-300 rounded text-slate-800"
                    placeholder="Dusun, Desa, Kecamatan, Kabupaten"
                  />
                </div>
              </div>
            </div>

            {/* CARD 2: PENGISIAN TITIK-TITIK KHUSUS DOKUMEN AKTIF */}
            <div className="bg-white p-3.5 rounded-xl border border-slate-200 shadow-2xs space-y-3">
              <h3 className="text-xs font-bold text-slate-800 uppercase flex items-center gap-1.5 border-b border-slate-200 pb-2">
                <Sparkles className="w-4 h-4 text-emerald-700" />
                <span>Isian Bagian Titik-Titik ({getLetterTypeLabel(jenisSurat)})</span>
              </h3>

              {/* 1. BPJS KK1 */}
              {jenisSurat === 'BPJS_KK1' && (
                <div className="space-y-2 text-xs">
                  <div>
                    <label className="block text-[10px] font-semibold text-slate-600 mb-0.5">Nama Perusahaan / Pemberi Kerja</label>
                    <input
                      type="text"
                      value={kkPerusahaan}
                      onChange={(e) => setKkPerusahaan(e.target.value)}
                      className="w-full px-2.5 py-1 border border-slate-300 rounded font-semibold"
                    />
                  </div>
                  <div className="grid grid-cols-2 gap-2">
                    <div>
                      <label className="block text-[10px] font-semibold text-slate-600 mb-0.5">Nomor NPP BPJS-TK</label>
                      <input
                        type="text"
                        value={kkNpp}
                        onChange={(e) => setKkNpp(e.target.value)}
                        className="w-full px-2 py-1 border border-slate-300 rounded font-mono"
                      />
                    </div>
                    <div>
                      <label className="block text-[10px] font-semibold text-slate-600 mb-0.5">Tanggal & Jam Kejadian</label>
                      <div className="flex gap-1">
                        <input
                          type="date"
                          value={kk1Tgl}
                          onChange={(e) => setKk1Tgl(e.target.value)}
                          className="w-full px-1.5 py-1 border border-slate-300 rounded text-xs"
                        />
                        <input
                          type="text"
                          value={kk1Jam}
                          onChange={(e) => setKk1Jam(e.target.value)}
                          className="w-20 px-1 py-1 border border-slate-300 rounded text-xs text-center"
                          placeholder="08:45 WIB"
                        />
                      </div>
                    </div>
                  </div>
                  <div>
                    <label className="block text-[10px] font-semibold text-slate-600 mb-0.5">Tempat Kejadian Kecelakaan</label>
                    <input
                      type="text"
                      value={kk1Tempat}
                      onChange={(e) => setKk1Tempat(e.target.value)}
                      className="w-full px-2.5 py-1 border border-slate-300 rounded"
                      placeholder="Area Pabrik / Perjalanan Kerja"
                    />
                  </div>
                  <div>
                    <label className="block text-[10px] font-semibold text-slate-600 mb-0.5">Kronologi Singkat Kecelakaan</label>
                    <textarea
                      rows={2}
                      value={kk1Kronologi}
                      onChange={(e) => setKk1Kronologi(e.target.value)}
                      className="w-full px-2.5 py-1 border border-slate-300 rounded text-xs"
                    />
                  </div>
                  <div>
                    <label className="block text-[10px] font-semibold text-slate-600 mb-0.5">Bagian Tubuh Yang Cidera</label>
                    <input
                      type="text"
                      value={kk1Cidera}
                      onChange={(e) => setKk1Cidera(e.target.value)}
                      className="w-full px-2.5 py-1 border border-slate-300 rounded font-semibold text-rose-800"
                    />
                  </div>
                </div>
              )}

              {/* 2. BPJS KK2 */}
              {jenisSurat === 'BPJS_KK2' && (
                <div className="space-y-2 text-xs">
                  <div>
                    <label className="block text-[10px] font-semibold text-slate-600 mb-0.5">Diagnosa Kecelakaan Kerja (Tahap II)</label>
                    <input
                      type="text"
                      value={kk2Diagnosa}
                      onChange={(e) => setKk2Diagnosa(e.target.value)}
                      className="w-full px-2.5 py-1 border border-slate-300 rounded font-semibold text-emerald-950"
                    />
                  </div>
                  <div className="grid grid-cols-2 gap-2">
                    <div>
                      <label className="block text-[10px] font-semibold text-slate-600 mb-0.5">Status Kemampuan Bekerja</label>
                      <select
                        value={kk2Stmb}
                        onChange={(e) => setKk2Stmb(e.target.value as any)}
                        className="w-full px-2 py-1 border border-slate-300 rounded text-xs font-semibold"
                      >
                        <option value="Sementara Tidak Mampu Bekerja (STMB)">Sementara Tidak Mampu Bekerja (STMB)</option>
                        <option value="Mampu Bekerja Ringan">Mampu Bekerja Ringan</option>
                        <option value="Sembuh Sempurna">Sembuh Sempurna</option>
                      </select>
                    </div>
                    <div>
                      <label className="block text-[10px] font-semibold text-slate-600 mb-0.5">Lama Istirahat / STMB (Hari)</label>
                      <input
                        type="number"
                        defaultValue={7}
                        className="w-full px-2 py-1 border border-slate-300 rounded text-xs"
                      />
                    </div>
                  </div>
                </div>
              )}

              {/* 3. BPJS KK3 */}
              {jenisSurat === 'BPJS_KK3' && (
                <div className="space-y-2 text-xs">
                  <div>
                    <label className="block text-[10px] font-semibold text-slate-600 mb-0.5">Keadaan Akhir Pasien (Tahap III / Penutupan Kasus)</label>
                    <select
                      value={kk3Keadaan}
                      onChange={(e) => setKk3Keadaan(e.target.value as any)}
                      className="w-full px-2 py-1 border border-slate-300 rounded font-bold text-emerald-950"
                    >
                      <option value="Sembuh tanpa cacat">Sembuh tanpa cacat</option>
                      <option value="Cacat fungsi">Cacat fungsi</option>
                      <option value="Cacat sebagian">Cacat sebagian</option>
                      <option value="Cacat total tetap">Cacat total tetap</option>
                      <option value="Meninggal dunia">Meninggal dunia</option>
                    </select>
                  </div>
                  <div>
                    <label className="block text-[10px] font-semibold text-slate-600 mb-0.5">Tanggal Bekerja Kembali</label>
                    <input
                      type="date"
                      value={kk3TglKembali}
                      onChange={(e) => setKk3TglKembali(e.target.value)}
                      className="w-full px-2.5 py-1 border border-slate-300 rounded text-xs"
                    />
                  </div>
                </div>
              )}

              {/* 4. PESAN KAMAR */}
              {jenisSurat === 'PESAN_KAMAR' && (
                <div className="space-y-2 text-xs">
                  <div>
                    <label className="block text-[10px] font-semibold text-slate-600 mb-0.5">Pilihan Nama Ruangan</label>
                    <input
                      type="text"
                      value={pesanRuangan}
                      onChange={(e) => setPesanRuangan(e.target.value)}
                      className="w-full px-2.5 py-1 border border-slate-300 rounded font-semibold"
                      placeholder="Ruang Perawatan Flamboyan / Melati / Bersalin"
                    />
                  </div>
                  <div className="grid grid-cols-2 gap-2">
                    <div>
                      <label className="block text-[10px] font-semibold text-slate-600 mb-0.5">Kelas Kamar</label>
                      <select
                        value={pesanKelasKamar}
                        onChange={(e) => handlePesanKelasChange(e.target.value as any)}
                        className="w-full px-2 py-1 border border-slate-300 rounded text-xs font-semibold"
                      >
                        {ROOM_CLASSES.map((r) => (
                          <option key={r.kelas} value={r.kelas}>
                            {r.kelas} (Rp {r.tarif.toLocaleString('id-ID')})
                          </option>
                        ))}
                      </select>
                    </div>
                    <div>
                      <label className="block text-[10px] font-semibold text-slate-600 mb-0.5">Tanggal & Jam Rencana Masuk</label>
                      <div className="flex gap-1">
                        <input
                          type="date"
                          value={pesanTglMasuk}
                          onChange={(e) => setPesanTglMasuk(e.target.value)}
                          className="w-full px-1.5 py-1 border border-slate-300 rounded text-xs"
                        />
                        <input
                          type="text"
                          value={pesanJamMasuk}
                          onChange={(e) => setPesanJamMasuk(e.target.value)}
                          className="w-20 px-1 py-1 border border-slate-300 rounded text-xs text-center"
                        />
                      </div>
                    </div>
                  </div>
                  <div className="grid grid-cols-2 gap-2">
                    <div>
                      <label className="block text-[10px] font-semibold text-slate-600 mb-0.5">Nama Pemesan / Keluarga</label>
                      <input
                        type="text"
                        value={pesanNamaPemesan}
                        onChange={(e) => setPesanNamaPemesan(e.target.value)}
                        className="w-full px-2 py-1 border border-slate-300 rounded text-xs"
                      />
                    </div>
                    <div>
                      <label className="block text-[10px] font-semibold text-slate-600 mb-0.5">Petugas Admisi RSUMB</label>
                      <input
                        type="text"
                        value={pesanPetugas}
                        onChange={(e) => setPesanPetugas(e.target.value)}
                        className="w-full px-2 py-1 border border-slate-300 rounded text-xs"
                      />
                    </div>
                  </div>
                </div>
              )}

              {/* 5. GAGAL FINGERPRINT */}
              {jenisSurat === 'GAGAL_FINGERPRINT' && (
                <div className="space-y-2 text-xs">
                  <div className="grid grid-cols-2 gap-2">
                    <div>
                      <label className="block text-[10px] font-semibold text-slate-600 mb-0.5">Nama Penanggung Jawab</label>
                      <input
                        type="text"
                        value={gagalNamaPj}
                        onChange={(e) => setGagalNamaPj(e.target.value)}
                        className="w-full px-2 py-1 border border-slate-300 rounded text-xs font-semibold"
                      />
                    </div>
                    <div>
                      <label className="block text-[10px] font-semibold text-slate-600 mb-0.5">Hubungan dgn Pasien</label>
                      <select
                        value={gagalHubungan}
                        onChange={(e) => setGagalHubungan(e.target.value as any)}
                        className="w-full px-2 py-1 border border-slate-300 rounded text-xs font-semibold"
                      >
                        <option value="Suami">Suami</option>
                        <option value="Istri">Istri</option>
                        <option value="Ayah">Ayah</option>
                        <option value="Ibu">Ibu</option>
                        <option value="Anak">Anak</option>
                        <option value="Lainnya">Lainnya</option>
                      </select>
                    </div>
                  </div>
                  <div className="grid grid-cols-3 gap-2">
                    <div>
                      <label className="block text-[10px] font-semibold text-slate-600 mb-0.5">Layanan</label>
                      <select
                        value={gagalLayanan}
                        onChange={(e) => setGagalLayanan(e.target.value as any)}
                        className="w-full px-2 py-1 border border-slate-300 rounded text-xs font-semibold"
                      >
                        <option value="Klinik">Klinik / Rawat Jalan</option>
                        <option value="IGD">IGD (Gawat Darurat)</option>
                        <option value="Ruang">Ruang Rawat Inap</option>
                      </select>
                    </div>
                    <div className="col-span-2">
                      <label className="block text-[10px] font-semibold text-slate-600 mb-0.5">Nama Klinik / Ruangan</label>
                      <input
                        type="text"
                        value={gagalNamaLayanan}
                        onChange={(e) => setGagalNamaLayanan(e.target.value)}
                        className="w-full px-2 py-1 border border-slate-300 rounded text-xs"
                      />
                    </div>
                  </div>
                  <div>
                    <label className="block text-[10px] font-semibold text-slate-600 mb-0.5">Alasan Kesulitan Rekam Sidik Jari</label>
                    <textarea
                      rows={2}
                      value={gagalAlasan}
                      onChange={(e) => setGagalAlasan(e.target.value)}
                      className="w-full px-2 py-1 border border-slate-300 rounded text-xs font-medium text-emerald-950"
                    />
                  </div>
                  <div className="grid grid-cols-2 gap-2">
                    <div>
                      <label className="block text-[10px] font-semibold text-slate-600 mb-0.5">Petugas Pembuat</label>
                      <input
                        type="text"
                        value={gagalPetugas}
                        onChange={(e) => setGagalPetugas(e.target.value)}
                        className="w-full px-2 py-1 border border-slate-300 rounded text-xs"
                      />
                    </div>
                    <div>
                      <label className="block text-[10px] font-semibold text-slate-600 mb-0.5">PIC Klaim BPJS RSUMB</label>
                      <input
                        type="text"
                        value={gagalPicKlaim}
                        onChange={(e) => setGagalPicKlaim(e.target.value)}
                        className="w-full px-2 py-1 border border-slate-300 rounded text-xs"
                      />
                    </div>
                  </div>
                </div>
              )}

              {/* 6. ADMEDIKA */}
              {jenisSurat === 'ADMEDIKA' && (
                <div className="space-y-2 text-xs">
                  <div className="grid grid-cols-2 gap-2">
                    <div>
                      <label className="block text-[10px] font-semibold text-slate-600 mb-0.5">No. Kartu AdMedika</label>
                      <input
                        type="text"
                        value={admNoKartu}
                        onChange={(e) => setAdmNoKartu(e.target.value)}
                        className="w-full px-2 py-1 border border-slate-300 rounded font-mono text-xs"
                      />
                    </div>
                    <div>
                      <label className="block text-[10px] font-semibold text-slate-600 mb-0.5">Perusahaan Penjamin</label>
                      <input
                        type="text"
                        value={admPerusahaan}
                        onChange={(e) => setAdmPerusahaan(e.target.value)}
                        className="w-full px-2 py-1 border border-slate-300 rounded text-xs font-semibold"
                      />
                    </div>
                  </div>
                  <div className="grid grid-cols-2 gap-2">
                    <div>
                      <label className="block text-[10px] font-semibold text-slate-600 mb-0.5">Jenis Layanan</label>
                      <select
                        value={admJenisLayanan}
                        onChange={(e) => setAdmJenisLayanan(e.target.value as any)}
                        className="w-full px-2 py-1 border border-slate-300 rounded text-xs font-bold"
                      >
                        <option value="Rawat Jalan">Rawat Jalan Spesialis / Umum</option>
                        <option value="Rawat Gigi">Pemeriksaan & Tindakan Gigi</option>
                      </select>
                    </div>
                    <div>
                      <label className="block text-[10px] font-semibold text-slate-600 mb-0.5">Status Pasien</label>
                      <select
                        value={admStatusPasien}
                        onChange={(e) => setAdmStatusPasien(e.target.value as any)}
                        className="w-full px-2 py-1 border border-slate-300 rounded text-xs"
                      >
                        <option value="Karyawan">Karyawan / Employee</option>
                        <option value="Istri/Suami">Istri / Suami</option>
                        <option value="Anak">Anak / Child</option>
                      </select>
                    </div>
                  </div>
                  <div>
                    <label className="block text-[10px] font-semibold text-slate-600 mb-0.5">Diagnosa Utama & ICD-10</label>
                    <div className="flex gap-1">
                      <input
                        type="text"
                        value={admDiagnosa}
                        onChange={(e) => setAdmDiagnosa(e.target.value)}
                        className="w-full px-2 py-1 border border-slate-300 rounded font-semibold text-xs"
                      />
                      <input
                        type="text"
                        value={admIcd10}
                        onChange={(e) => setAdmIcd10(e.target.value)}
                        className="w-20 px-1 py-1 border border-slate-300 rounded font-mono text-center text-xs font-bold"
                      />
                    </div>
                  </div>
                  <div>
                    <label className="block text-[10px] font-semibold text-slate-600 mb-0.5">Terapi Obat / Tindakan</label>
                    <input
                      type="text"
                      value={admTindakan}
                      onChange={(e) => setAdmTindakan(e.target.value)}
                      className="w-full px-2 py-1 border border-slate-300 rounded text-xs"
                    />
                  </div>
                </div>
              )}

              {/* 7. SKBN */}
              {jenisSurat === 'SKBN' && (
                <div className="space-y-2 text-xs">
                  <p className="text-[11px] font-semibold text-slate-700">Hasil Uji Skrining 6 Parameter Urine Strip:</p>
                  <div className="grid grid-cols-3 gap-1.5 text-[10.5px]">
                    {[
                      { l: 'AMP (Inex)', v: skbnAmp, s: setSkbnAmp },
                      { l: 'MET (Shabu)', v: skbnMet, s: setSkbnMet },
                      { l: 'COC (Kokain)', v: skbnCoc, s: setSkbnCoc },
                      { l: 'THC (Ganja)', v: skbnThc, s: setSkbnThc },
                      { l: 'MOP (Morfin)', v: skbnMop, s: setSkbnMop },
                      { l: 'BZO (Sedatif)', v: skbnBzo, s: setSkbnBzo }
                    ].map((item, i) => (
                      <div key={i} className="border border-slate-200 p-1 rounded bg-slate-50">
                        <div className="font-bold truncate text-[10px]">{item.l}</div>
                        <select
                          value={item.v}
                          onChange={(e) => item.s(e.target.value as any)}
                          className={`w-full text-[10px] font-bold py-0.5 rounded ${item.v === 'Negatif' ? 'bg-emerald-100 text-emerald-800' : 'bg-rose-100 text-rose-800'}`}
                        >
                          <option value="Negatif">Negatif</option>
                          <option value="Positif">Positif</option>
                        </select>
                      </div>
                    ))}
                  </div>
                </div>
              )}

              {/* 8. SEHAT & DOKTER */}
              {jenisSurat === 'SEHAT' && (
                <div className="grid grid-cols-3 gap-2 text-xs">
                  <div>
                    <label className="block text-[10px] text-slate-600">TB (cm)</label>
                    <input type="number" value={sehatTb} onChange={(e) => setSehatTb(Number(e.target.value))} className="w-full px-2 py-1 border border-slate-300 rounded" />
                  </div>
                  <div>
                    <label className="block text-[10px] text-slate-600">BB (kg)</label>
                    <input type="number" value={sehatBb} onChange={(e) => setSehatBb(Number(e.target.value))} className="w-full px-2 py-1 border border-slate-300 rounded" />
                  </div>
                  <div>
                    <label className="block text-[10px] text-slate-600">Tekanan Darah</label>
                    <input type="text" value={sehatTd} onChange={(e) => setSehatTd(e.target.value)} className="w-full px-2 py-1 border border-slate-300 rounded" />
                  </div>
                </div>
              )}

              {jenisSurat === 'DOKTER' && (
                <div className="space-y-2 text-xs">
                  <div>
                    <label className="block text-[10px] text-slate-600">Diagnosa Penyakit</label>
                    <input type="text" value={dokterDiagnosa} onChange={(e) => setDokterDiagnosa(e.target.value)} className="w-full px-2 py-1 border border-slate-300 rounded font-semibold" />
                  </div>
                  <div className="grid grid-cols-2 gap-2">
                    <div>
                      <label className="block text-[10px] text-slate-600">Lama Istirahat (Hari)</label>
                      <input type="number" value={dokterLamaHari} onChange={(e) => setDokterLamaHari(Number(e.target.value))} className="w-full px-2 py-1 border border-slate-300 rounded" />
                    </div>
                    <div>
                      <label className="block text-[10px] text-slate-600">Tanggal Mulai</label>
                      <input type="date" value={dokterTglMulai} onChange={(e) => setDokterTglMulai(e.target.value)} className="w-full px-2 py-1 border border-slate-300 rounded" />
                    </div>
                  </div>
                </div>
              )}
            </div>

            {/* CARD 3: DOKTER / PETUGAS PENANDATANGAN */}
            <div className="bg-white p-3.5 rounded-xl border border-slate-200 shadow-2xs space-y-2.5">
              <label className="text-xs font-bold text-slate-800 uppercase flex items-center gap-1.5">
                <Stethoscope className="w-4 h-4 text-emerald-700" />
                <span>Dokter DPJP / Penandatangan Resmi</span>
              </label>

              <select
                value={dokterId}
                onChange={(e) => setDokterId(e.target.value)}
                className="w-full px-3 py-1.5 border border-slate-300 rounded-lg text-xs font-bold text-slate-800"
              >
                {MASTER_LETTER_DOCTORS.map((doc) => (
                  <option key={doc.id} value={doc.id}>
                    {doc.nama} - {doc.spesialisasi} (SIP: {doc.sip})
                  </option>
                ))}
              </select>

              <div>
                <label className="block text-[10px] font-semibold text-slate-600 mb-0.5">Keperluan Pembuatan Surat</label>
                <input
                  type="text"
                  value={keperluan}
                  onChange={(e) => setKeperluan(e.target.value)}
                  className="w-full px-2.5 py-1 border border-slate-300 rounded text-xs"
                  placeholder="Persyaratan Klaim Resmi / Administrasi"
                />
              </div>
            </div>

            {/* Bottom Actions for Mobile */}
            <div className="pt-2 flex items-center justify-end gap-2 lg:hidden">
              <button
                type="button"
                onClick={() => setMobileTab('preview')}
                className="w-full py-2 bg-[#005d42] text-white rounded-lg text-xs font-bold text-center flex items-center justify-center gap-1.5"
              >
                <Eye className="w-4 h-4" />
                <span>Lihat Pratinjau Dokumen</span>
              </button>
            </div>
          </div>

          {/* ======================================================== */}
          {/* SISI KANAN: PRATINJAU & SIAP CETAK (A4 / FOLIO)           */}
          {/* ======================================================== */}
          <div className={`lg:col-span-7 flex flex-col bg-slate-300/70 overflow-hidden relative ${mobileTab === 'form' ? 'hidden lg:flex' : 'flex'}`}>
            
            {/* Top Toolbar Pratinjau */}
            <div className="bg-slate-800 text-slate-200 px-4 py-2 flex items-center justify-between border-b border-slate-700 shrink-0 text-xs print:hidden no-print">
              <div className="flex items-center gap-2">
                <span className="inline-flex items-center gap-1 text-[11px] font-bold text-emerald-400 bg-emerald-950/60 px-2 py-0.5 rounded border border-emerald-800">
                  <span className="w-2 h-2 rounded-full bg-emerald-400 animate-pulse" />
                  Pratinjau Otomatis Real-Time
                </span>
                <span className="text-[11px] text-slate-400 hidden sm:inline">
                  Format Kertas: A4 / Folio (210 &times; 297 mm)
                </span>
              </div>

              <div className="flex items-center gap-2">
                <div className="flex items-center gap-1 bg-slate-900 px-2 py-1 rounded text-[11px]">
                  <button
                    type="button"
                    onClick={() => setPreviewZoom(Math.max(65, previewZoom - 10))}
                    className="hover:text-white"
                    title="Zoom Out"
                  >
                    <ZoomOut className="w-3.5 h-3.5" />
                  </button>
                  <span className="font-mono w-10 text-center">{previewZoom}%</span>
                  <button
                    type="button"
                    onClick={() => setPreviewZoom(Math.min(120, previewZoom + 10))}
                    className="hover:text-white"
                    title="Zoom In"
                  >
                    <ZoomIn className="w-3.5 h-3.5" />
                  </button>
                </div>

                <button
                  type="button"
                  onClick={handlePrint}
                  className="flex items-center gap-1.5 px-3 py-1 bg-emerald-600 hover:bg-emerald-500 text-white rounded font-bold transition-all shadow-sm"
                >
                  <Printer className="w-3.5 h-3.5" />
                  <span>Cetak</span>
                </button>
              </div>
            </div>

            {/* Interactive Scrollable Canvas with Sheet */}
            <div className="flex-1 overflow-y-auto overflow-x-auto p-4 sm:p-8 flex justify-center items-start print:p-0 print:m-0 print:overflow-visible print:bg-white">
              <div
                style={{
                  transform: `scale(${previewZoom / 100})`,
                  transformOrigin: 'top center',
                  transition: 'transform 0.15s ease-out'
                }}
                className="w-full max-w-[210mm] min-h-[297mm] transition-all print:scale-100 print:transform-none print:max-w-none print:w-full"
              >
                <DocumentSheetRenderer letter={previewLetter} />
              </div>
            </div>

            {/* Bottom Bar: Action Save & Print */}
            <div className="bg-white border-t border-slate-200 px-4 py-3 flex items-center justify-between shrink-0 print:hidden no-print">
              <div className="text-xs text-slate-500 hidden sm:block">
                Dokumen siap cetak dengan Kop Surat & Tanda Tangan RSUMB.
              </div>

              <div className="flex items-center gap-2 w-full sm:w-auto justify-end">
                <button
                  type="button"
                  onClick={onClose}
                  className="px-3 py-1.5 bg-slate-100 hover:bg-slate-200 text-slate-700 rounded-lg text-xs font-semibold"
                >
                  Batal
                </button>

                <button
                  type="button"
                  onClick={() => handleFormSubmit(false)}
                  className="flex items-center gap-1.5 px-4 py-1.5 bg-slate-800 hover:bg-slate-700 text-white rounded-lg text-xs font-bold transition-colors"
                >
                  <Save className="w-3.5 h-3.5" />
                  <span>Simpan Dokumen</span>
                </button>

                <button
                  type="button"
                  onClick={() => handleFormSubmit(true)}
                  className="flex items-center gap-1.5 px-5 py-1.5 bg-[#005d42] hover:bg-[#004833] text-white rounded-lg text-xs font-bold transition-all shadow-md shadow-emerald-950/20 active:scale-95 cursor-pointer"
                >
                  <Printer className="w-3.5 h-3.5" />
                  <span>🖨️ Cetak / Simpan Document</span>
                </button>
              </div>
            </div>
          </div>
        </div>
      </div>
    </div>
  );
};
